### ISSUE TITLE
Incompatibility of Retentaion App with Nextcloud 28 Preventing NextCloud Upgrade

### ISSUE THREAD

**Issue by gseilheimer** [nextcloud/files_retention#434] opened 2023-12-13 18:05 UTC
**Issue Description:**
I am encountering an issue with the [retenteion](https://apps.nextcloud.com/apps/files_retention) app in the context of the latest Nextcloud 28 update. It appears that Retentaion has not been updated to be compatible with Nextcloud 28, which is preventing the upgrade of our Nextcloud instance.

Expected Behavior:
The expectation is that KeyWeb should seamlessly integrate with Nextcloud 28, allowing for a smooth upgrade process of Nextcloud.

Actual Behavior:
The upgrade process is halted due to the incompatibility issue, with [include specific error messages or behaviors observed].

Compatible versions are missing for these apps 
[Retention ↗](https://apps.nextcloud.com/apps/files_retention)
[Keeweb ↗](https://apps.nextcloud.com/apps/keeweb)

**Comment by tflidd** [comment] 2023-12-13 21:44
Duplicate of https://github.com/nextcloud/files_retention/issues/433

**Closed** 2023-12-13 22:17 UTC
