### ISSUE TITLE
Deleted documents do not appear within the trash bin

### ISSUE THREAD

**Issue by Chingato** [nextcloud/files_retention#34] opened 2017-06-06 18:38 UTC
Hello,

I identified an issue with the deleted documents. They are not added to the trash bin.

Can you please check.

Thanks a lot
Chingato

### Steps to reproduce
1. Upload a new file
2. wait until the file is deleted based on the assigned retention rule (tag)
3. document is permanently deleted and not added to the trash bin

### Expected behaviour
There should be a possible to restore automatically deleted documents. The official app "Deleted files" is activated but the deleted documents do not appear within the trash bin.

### Actual behaviour
At the moment the document is deleted without any kind of notification or approval and is not visible within the trash bin of the Nextcloud account.
If documents are _manually_ deleted by the user these documents are added to the trash bin but not if the _deletion is triggered via the Retention app_.

### Server configuration

**Operating system**:
Debian 8 (Jessie) _- basis is OSMC media center derivative_

**Web server:**
Apache/2.4.10 (Debian)

**Database:**
10.0.30-0+deb8u2

**PHP version:**
 7.0.19-1 (cli)

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Where did you install Nextcloud from:**
ZIP file

**List of activated apps:**
Retention (version 1.1.2)
Nextant
Files automated tagging

**Comment by amzen** [comment] 2018-10-23 07:30
Hello,

I confirm this behaviour of the file retention app.
It would be nice if the deletion rule of file retention follow the regular file retention rule.

So I'm surprised to see no answer to chingato's warning because this retention app plays a key role with the GDPR to monitor the time users are keeping files.

**Comment by nickvergessen** [comment] 2018-10-23 09:31
> I'm surprised to see no answer to chingato's warning because this retention app plays a key role with the GDPR to monitor the time users are keeping files.

That is exactly the point. Some industries rules say files have to be deleted, not to be moved to a trashbin.

**Comment by amzen** [comment] 2018-10-23 09:41
Hello Nick, 
I was surprised with this behaviour, and now I agree with your position "files have to be deleted, not to be moved to a trashbin".
This is interessing to be documented as a GDPR requirement. I'l do it with my users.

**Comment by Chingato** [comment] 2018-10-23 09:59
Hello Nick,

I do only partly agree. Let me explain why I raised this request.

Background:
==========
I worked a lot with Records Management experts of big clients (100k+ employee). Mainly in the area of storing HR related documents.
The requirement from legal departments was always to add a confirmation/approval step to the deletion process. No-one trusts automatic deletion rules and expects someone to finally approve the deletion.

As it is not possible to add such an approval step to the document deletion workflow I raised this request to store the documents at least within the trash bin.
This request would be obsolete if it is possible to configure an approval step. Is this possible?

Thanks.

**Comment by nickvergessen** [comment] 2018-10-23 10:10
@Chingato yeah your request is still valid and considered a nice addition as an option.
I was just explaining the "strange" default behaviour.

**Comment by sualko** [comment] 2021-02-19 13:20
We experienced inconsistent behavior during the retention process. Sometimes they get moved to the trash bin and sometimes they get deleted completely. After looking at the code of the trash bin app it looks like that both apps are not bootstrapped in persistent order. Since the trash bin app is using legacy events, they probably could not use the full potential of new bootstrapping process. As a workaround it should be enough to remove the following lines from the info.xml. Can someone test this?

https://github.com/nextcloud/files_retention/blob/30833d3c12fc05317375bf6394da119fa368c4d1/appinfo/info.xml#L13-L15

**Comment by sualko** [comment] 2021-02-19 13:24
Btw. since this app is not listening for the `MoveToTrashEvent` moving files to the trash bin should be the default behavior if everything is bootstrapped correctly. Maybe it would be a good idea to add another option to the configuration to distinguish between move to trash bin / delete. Can you up vote this comment if you would like to have such functionality?

**Comment by sualko** [comment] 2021-02-20 12:45
Ok, I checked the NC bootstrapping and there is only one case in which not all apps get loaded and even if one is loaded before the other this should not influence the behavior. Therefore the removal of the filesystem type is probably right, it will not influence anything. In my latest tests everything gets always moved to the trash bin. As mentioned to enable permanent deletion the app has to be extended to use the `MoveToTrashEvent`.

**Comment by nickvergessen** [comment] 2021-02-20 15:06
Deleting that seems wrong as its a filesystem app.
Can it be fixed by adding the dav type additionally? This fixed a file related bug in Talk lately

**Comment by sualko** [comment] 2021-02-20 17:36
> Deleting that seems wrong as its a filesystem app.

What's the definition of a filesystem app, because it's not providing any filesystem functionality. It's just working with the filesystem as many apps do.

> Can it be fixed by adding the dav type additionally?

Since the "magic" happens in the background job which is executed by the cron.php file, I think it's not related to the app type. The main issue is that it is not reproducible for me that sometimes things get deleted and somtimes they get moved to the trash bin (that should be the correct behavior, even if it is not the desired one). We try to add more debug output to get a better understanding what is going on.

**Comment by nickvergessen** [comment] 2021-02-20 18:05
I think it could be fixed with https://github.com/nextcloud/files_retention/pull/106

Seems like this was not released yet. I guess it will come next week or the week after with the 21 compatibility

**Comment by sualko** [comment] 2021-02-20 18:09
I was using a custom build with my pending pull requests, so this change was included, but let's see how the next retentions will work. Btw thanks for taking the time to answer this issue :clap:

**Comment by nickvergessen** [comment] 2021-02-23 17:34
So did it work?

**Closed** 2021-04-14 09:07 UTC
